17.MyFirstWebApp-PhoneBook/MyFirstWebApp-PhoneBook/Models/Contact.cs
using System.ComponentModel.DataAnnotations;

namespace MyFirstWebApp_PhoneBook.Models
{
    public class Contact
    {
        [Required(ErrorMessage = "The field {0} is required!")]
        public string Name { get; set; }

        [Required(ErrorMessage = "The field {0} is required!")]
        [StringLength(15, MinimumLength = 5, ErrorMessage = "The length of the field {0} must be between {2} and {1}")]
        public string Number { get; set; }
    }
}

17.MyFirstWebApp-PhoneBook/MyFirstWebApp-PhoneBook/Models/DataContext.cs
using System.Collections.Generic;

namespace MyFirstWebApp_PhoneBook.Models
{
    public class DataContext
    {
        public static List<Contact> Contacts { get; set; }
    }
}

17.MyFirstWebApp-PhoneBook/MyFirstWebApp-PhoneBook/Models/ErrorViewModel.cs
using System;

namespace MyFirstWebApp_PhoneBook.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

17.MyFirstWebApp-PhoneBook/MyFirstWebApp-PhoneBook/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyFirstWebApp_PhoneBook.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MyFirstWebApp_PhoneBook.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

17.MyFirstWebApp-PhoneBook/MyFirstWebApp-PhoneBook/Controllers/PhoneBookController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstWebApp_PhoneBook.Models;

namespace MyFirstWebApp_PhoneBook.Controllers
{
    public class PhoneBookController : Controller
    {
        public IActionResult Index()
        {
            return View(DataContext.Contacts);
        }

        [HttpPost]
        public IActionResult Add(Contact model)
        {
            if (ModelState.IsValid)
            {
                DataContext.Contacts.Add(model);
            }
            else
            {
                TempData["Error"] = "Incorrect data!";
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

17.MyFirstWebApp-PhoneBook/MyFirstWebApp-PhoneBook/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

17.MyFirstWebApp-PhoneBook/MyFirstWebApp-PhoneBook/Views/PhoneBook/Index.cshtml
@model List<Contact>
@{
    ViewData["Title"] = "Contacts";
}

<head>
    <title>Phonebook</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>

<div class="row">
    <div class="col-md-4">
        <h3>Phonebook</h3>
        <table class="table">
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                        @item.Name
                        </td>
                        <td>
                        @item.Number
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <div class="text-danger">
            @(TempData["Error"] != null ? TempData["Error"] : string.Empty) 
        </div>

        @using (Html.BeginForm("Add", "PhoneBook", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <legend>New Contact</legend>
            <div class="form-group">
                <label for="name" class="col-lg-2 control-label">Name</label>
                <div class="col-lg-10">
                    <input type="text" autofocus="autofocus" name="name" title="Name" class="form-control" id="name" />
                </div>
            </div>
            <div class="form-group">
                <label for="number" class="col-lg-2 control-label">Number</label>
                <div class="col-lg-10">
                    <input type="text" autofocus="autofocus" name="number" title="Number" class="form-control" id="number" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-10 col-lg-offset-2">
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
            </div>
        }
    </div>
</div>

17.MyFirstWebApp-PhoneBook/MyFirstWebApp-PhoneBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFirstWebApp_PhoneBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PhoneBook</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PhoneBook" asp-action="Index">Phone book</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MyFirstWebApp_PhoneBook - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>